project:
  type: book
  output-dir: docs

about:
  template: solana
  # links:
  #   - icon: twitter
  #     text: twitter
  #     href: https://x.com/UrbanDemog
  #   - icon: github
  #     text: Github
  #     href: https://github.com/ipeaGIT/censobr_oficina_abep_2024

execute:
  freeze: auto
#  cache: true
lang: pt
book:
  title: "{censobr}: Explorando o Censo Demográfico em R"
  author: 
  - name: "Rafael H. M. Pereira"
    email: rafael.pereira@ipea.gov.br
    url: https://www.urbandemographics.org
    orcid: 0000-0003-2125-7465
    affiliation: "Instituto de Pesquisa Econômica Aplicada (Ipea)"
  - name: "Rogerio Barbosa"
    url: https://iesp.uerj.br/pesquisador/rogerio-jeronimo-barbosa
    orcid: 0000-0003-2125-7465
    affiliation: "Instituto de Estudos Sociais e Políticos (IESP/UERJ)"
  chapters:
    - index.qmd
    - 2_instalacao.qmd
    - 3_info_censo.qmd
    - 4_microdados.qmd
    - 5_agregados_setores.qmd
    - 6_documentacao.qmd


  site-url: https://ipeagit.github.io/censobr_oficina_abep_2024/
  repo-url: https://github.com/ipeaGIT/censobr_oficina_abep_2024
  favicon: /images/favicon.png
  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/ipeaGIT/censobr_oficina_abep_2024
      - icon: twitter
        text: twitter
        href: https://x.com/UrbanDemog
      - icon: linkedin
        text: linkedin
        href: https://www.linkedin.com/in/rafael-h-m-pereira/
  page-navigation: true
  page-footer: 
    border: false
    left: "Copyright 2024, Rafael H. M. Pereira" 
    right: 
      - icon: github
        href: https://github.com/ipeaGIT/censobr_oficina_abep_2024

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

bibliography: references.bib

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

google-scholar: true
code-link: true
